### ISSUE TITLE
URL Redirect 待改进

### ISSUE THREAD

**Issue by hex0wn** [momosecurity/rhizobia_P#2]
项目原demo，这样设置白名单的结果是允许跳转到`protect.domain`的所有子域。
```
$white=[".protect.domain"];
if(!$this->securityUtil->verifyRedirectUrl($url,$white)){
    return ;   //非法url
}
// 处理业务逻辑
```
问题：
1. 有些情况下需要跳转地址只允许是当前域名`protect.domain`，不允许跳转到任何子域，那么该如何设置？
2. 如果不够理解源码，想当然地使用`$white=["protect.domain"];`来解决上述问题，会导致`preg_match("/" . str_replace(".", "\\.", $item) . "$/i", $host)` 这个校验可以被域名`xxprotect.domain`绕过

建议：
  增加对单个域名的白名单支持
  对输入容错，开发不够熟悉api的情况下传入了错误的参数，sdk应该对其进行处理，保证不出现安全漏洞

**Comment by kimi-byte** [comment]
感谢建议，我们将于下周对URL Redirect防护方法进行改进

**Comment by kimi-byte** [comment]
我们已对URL Redirect防护方法进行了优化，域名白名单设置及生效方式如下：
```
//仅信任域名protect.domain
$white="protect.domain";
//仅信任protect.domain所有子域
$white=".protect.domain";
//信任多个域名的子域名或多个域名
$white=array(".protect.domain","protect1.domain"，".protect2.domain","protect3.domain");
```
可在https://github.com/momosecurity/rhizobia_P/blob/develop/src/URLSecurity/DefenseAgainstRedirect.php 查看变更后的内容。

**Comment by hex0wn** [comment]
改进很棒。我对代码做了一些调整 #4
