### ISSUE TITLE
单例

### ISSUE THREAD

**Issue by 8090Lambert** [momosecurity/rhizobia_P#8]
src/SecurityUtil.php 类中，如果要做单例是需要把 getinstance 方法的可见性设置为 protected 或者 private，如果不是单例，允许去new实例化，那是否应该在 __construct 方法中保证有和 getinstance 方法相同的逻辑

**Comment by kimi-byte** [comment]
“src/SecurityUtil.php 类中，如果要做单例是需要把 getinstance 方法的可见性设置为 protected 或者 private”

以上，单例模式，可调整__construct 为private实现，如下：
```   
    private static $securityUtil;
    /**
     * SecurityUtil constructor.
     */
    private function __construct()
    {
    }
    
    /**
     * @return SecurityUtil
     */
    public static function getInstance()
    {
        if (isset(self::$securityUtil)) {
            return self::$securityUtil;
        }
        self::$securityUtil = new SecurityUtil();
        return self::$securityUtil;
    }
```

为适应更多的场景，SecurityUtil类非严格的单例模式，当场景如向整个系统全局地提供单一实例时，可SecurityUtil::getInstance，当场景如加解密时，保证不同的key之间不会相应影响，可new实例。
具体根据业务场景选择。
